[project]
name = "kserving"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pytest>=8.3.3",
    "ray[data,serve,train,tune]>=2.39.0",
    "torch>=2.5.1",
    "torchvision>=0.20.1",
]
