x-common-args: &x-common-args
  PROJECT_DIR: "."

services:

  frontend:
    build:
      context: ../.. #/frontend
      dockerfile: frontend/Dockerfile
      args:
        <<: *x-common-args
    environment:
      - GATEWAY_SERVICE=http://gateway:5000
    ports:
      - "8501:8501"
    networks:
      - local-network
    depends_on:
      - gateway

  gateway:
    build:
      context: ../.. #/gateway
      dockerfile: gateway/Dockerfile
      args:
        <<: *x-common-args
    environment:
      - MODEL_SERVICE=http://model:8080/predictions/densenet
    ports:
      - "5000:5000"
    networks:
      - local-network

  model:
    build:
      context: ../.. #/model
      dockerfile: model/DockerfileTS
      args:
        <<: *x-common-args
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - local-network
  
networks:
  local-network:
    driver: bridge
