artifact_uri: file:///home/fahad/study/kserving/runs/mlflow/609382537381128781/1edadfefc8574e0c83ca4dee201fdf3f/artifacts
end_time: 1733071581852
entry_point_name: ''
experiment_id: '609382537381128781'
lifecycle_stage: active
run_id: 1edadfefc8574e0c83ca4dee201fdf3f
run_name: TorchTrainer_bcc01_00000
run_uuid: 1edadfefc8574e0c83ca4dee201fdf3f
source_name: ''
source_type: 4
source_version: ''
start_time: 1733071562133
status: 4
tags: []
user_id: unknown
